service: arbx-log-store

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  ArbXLogsTable:
    name: !Ref ArbXLogsTable
    arn: !GetAtt ArbXLogsTable.Arn

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 256
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ArbXLogsTable, Arn]
  environment:
    LOGS_TABLE: ${self:custom.ArbXLogsTable.name}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    ArbXLogsTable: ${file(tables/arbXLogsTable.yml):ArbXLogsTable}
