export const SUPPORTED_SERUM_MARKETS: Set<string> = new Set([
  "xCOPE-USDC",
  "soSUSHI-USDC",
  "soALEPH-USDC",
  "BTC-USDC",
  "soETH-USDC",
  "SRM-USDC",
  "soSXP-USDC",
  "soFTT-USDC",
  "soYFI-USDC",
  "soLINK-USDC",
  "soHGET-USDC",
  "soCREAM-USDC",
  "soUBXT-USDC",
  "soHNT-USDC",
  "soFRONT-USDC",
  "soAKRO-USDC",
  "soHXRO-USDC",
  "soUNI-USDC",
  "soMATH-USDC",
  "soTOMO-USDC",
  "soLUA-USDC",
  "SRM-SOL",
  "SOL-USDC",
  "FIDA-USDC",
  "KIN-USDC",
  "MAPS-USDC",
  "soKEEP-USDC",
  "soETH-USDT",
  "soSXP-USDT",
  "soCEL-USDT",
  "soALEPH-USDT",
  "soCREAM-USDT",
  "soKEEP-USDT",
  "soHNT-USDT",
  "FIDA-USDT",
  "soRSR-USDT",
  "SRM-USDT",
  "RAY-USDT",
  "BTC-USDT",
  "soFTT-USDT",
  "soAKRO-USDT",
  "soUNI-USDT",
  "soUBXT-USDT",
  "SOL-USDT",
  "soLUA-USDT",
  "soSUSHI-USDT",
  "soMATH-USDT",
  "soHGET-USDT",
  "soFRONT-USDT",
  "soTOMO-USDT",
  "soAAVE-USDT",
  "MAPS-USDT",
  "soHXRO-USDT",
  "KIN-USDT",
  "soYFI-USDT",
  "soLINK-USDT",
  "soSWAG-USDT",
  "USDT-USDC",
  "OXY-USDT",
  "OXY-USDC",
  "COPE-USDC",
  "MER-USDT",
  "MER-USDC",
  "SNY-USDC",
  // "SLRS-USDC",
  "ETHV-USDT",
  "IETHV-USDT",
  "SBR-USDC",
  // "renBTC-USDC",
  "renDOGE-USDC",
  "DXL-USDC",
  "MNGO-USDC",
  "CYS-USDC",
  "POLIS-USDC",
  "ATLAS-USDC",
  "LIKE-USDC",
  "MSOL-USDC",
  "MSOL-SOL",
  "AAVE-USDC",
  "AAVE-USDT",
  "AKRO-USDC",
  "AKRO-USDT",
  "ALEPH-USDC",
  "ALEPH-USDT",
  "CREAM-USDC",
  "ETH-USDC",
  "ETH-USDT",
  "FRONT-USDC",
  "FTT-USDC",
  "FTT-USDT",
  "HGET-USDC",
  "HGET-USDT",
  "HXRO-USDC",
  "HXRO-USDT",
  "LINK-USDC",
  "LINK-USDT",
  "MATH-USDC",
  "MATH-USDT",
  "RAY-USDC",
  "SUSHI-USDC",
  "SUSHI-USDT",
  "SXP-USDC",
  "SXP-USDT",
  "UNI-USDC",
  "UNI-USDT",
  "YFI-USDC",
  "YFI-USDT",
  "AVAX-USDC",
  // "AXSet-USDC",
  "BNB-USDC",
  "BNB-USDT",
  "MATICpo-USDC",
  "ROSE-USDC",
  // "SAND-USDC",
  // "SHIB-USDC",
  // "UST-USDC",
  // "JET-USDC",
  // "scnSOL-USDC",
  "stSOL-USDC",
  "GMT-USDC",
]);

export const SUPPORTED_RAYDIUM_MARKETS_ADDRESSES: Map<string, string> = new Map(
  Object.entries({
    "ATLAS-USDC": "2bnZ1edbvK3CK3LTNZ5jH9anvXYCmzPR4W2HQ6Ngsv5K",
    "ALEPH-USDC": "2Cat6zKJm5HRsqKs7W14cuzdrDQXByu8c9bAFcM9uHvY",
    "USDT-USDC": "2EXiumdi14E9b8Fy62QcA5Uh6WdHS2b38wtSxp72Mibj",
    "HXRO-USDC": "2KpMpqMH5bUcTkq5b8cYrSjQ173iARnD8SBGfkwXjk8W",
    "MNGO-USDC": "34tFULRrRwh4bMcBLPtJaNqqe5pVgGZACi5sR8Xz95KC",
    "soFTT-USDC": "4C2Mz1bVqe42QDDTyJ4HFCFFGsH5YDzo91Cen5w5NGun",
    "SOL-USDC": "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2",
    "SNY-USDC": "5TgJXpv6H3KJhHCuP7KoDLSCmi8sM8nABizP7CmYAKm1",
    "stSOL-USDC": "6a1CsrpeZubDjEJE9s1CMVheB6HWM5d7m1cj2jkhyXhj",
    "BTC-USDC": "6kbC5epG18DF2DwPEW34tBy5pGFS7pEGALR3v5MGxgc5",
    "RAY-USDC": "6UmmUiYoBjSrhakAobJw8BvkmJtDVxaeBtbt7rxWo1mg",
    "SOL-USDT": "7XawhbbxtsRcQA8KTkHT9f9nc6d69UwqCDh6U5EEbEmX",
    "UNI-USDC": "8J5fa8WBGaDSv8AUpgtqdh9HM5AZuSf2ijvSkKoaCXCi",
    "SRM-USDC": "8tzS7SkUZyHPQY7gLqsMCXZ5EDCgjESUHcB17tiR1h3Z",
    "SUSHI-USDC": "9SWy6nbSVZ44XuixEvHpona663pZPpVgzXQ3N7muG4ou",
    "POLIS-USDC": "9xyCzsHi1wUWva7t5Z8eAvZDRmUCVhRrbaFfm3VbU4Mf",
    "soETH-USDC": "AoPebtuJC4f2RweZSxcVCcdeTgaEXY64Uho8b5HdPxAR",
    "DXL-USDC": "asdEJnE7osjgnSyQkSZJ3e5YezbmXuDQPiyeyiBxoUm",
    "MER-USDC": "BkfGDk676QFtTiGxn7TtEpHayJZRr6LgNk9uTV2MH4bR",
    "COPE-USDC": "DiWxV1SPXPNJRCt5Ao1mJRAxjw97hJVyj8qGzZwFbAFb",
    "RAY-USDT": "DVa7Qmb5ct9RCpaU7UTpSaf3GVMYz17vNVU67XpdCRut",
    "ETH-USDC": "EoNrn8iUhwgJySD1pHu8Qxm5gSQqLK3za4m8xzD2RuEb",
    "soHXRO-USDC": "EU766cQ9GopWyRHXa12NpdjwhiiGyn2jRR9Gk4K4Cb1d",
    "SRM-SOL": "EvWJC2mnmu9C9aQrsJLXw8FhUcwBzFEUQsP1E5Y6a5N7",
    "BNB-USDC": "Fb1WR1kYvG1tHu4pwAxXQpdKT8Grh9i7ES9rZusLg7D6",
    "soALEPH-USDC": "GDHXjn9wF2zxW35DBkCegWQdoTfFBC9LXt7D5ovJxQ5B",
    "LIKE-USDC": "GmaDNMWsTYWjaXVBjJTHNmCWAKU6cn5hhtWWYEZt4odo",
  }),
);
