ArbXLogsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ArbXLogsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: uuid
        AttributeType: S
      - AttributeName: pubkey
        AttributeType: S
    KeySchema:
      - AttributeName: uuid
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: PublicKeyIndex
        KeySchema:
          - AttributeName: pubkey
            KeyType: HASH
        Projection:
          ProjectionType: 'ALL'
